version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev 
    command: gunicorn root.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/app/
    ports:
      - 8002:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=ecommerce
  redis:
    image: "redis:alpine"
  celery:
    build: .
    command: celery -A root worker -l info
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A root beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

volumes:
  postgres_data: