FROM python:3.10.5-slim-buster

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get -y update \
  && apt-get -y install netcat gcc \ 
  && apt-get -y install nano \
  && apt-get clean

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install --verbose -r requirements.txt

COPY ./entrypoint.sh /app/
RUN sed -i 's/\r$//g' /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

COPY . .

ENTRYPOINT ["sh", "/app/entrypoint.sh"]