version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile 
    command: gunicorn root.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/app/
    ports:
      - 8002:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=ecommerce
volumes:
  postgres_data: